
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-final-assignment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nakamasato/kubernetes-basics.git
    targetRevision: add-argocd-final-assignment
    path: argocd-test
  destination:
    server: https://kubernetes.default.svc
    namespace: master
  syncPolicy:
    automated: {}
