apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  data.csv: bmFtZSxhZ2UsZW1haWwscGFzc3dvcmQKbmFrYSwxLG5ha2FAZXhhbXBsZS5jb20sajRnbjQzZzRncgp0YW5ha2EsMix0YW5ha2FAZXhhbXBsZS5jb20sOGo0Mzdma3czdg==

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: [ "sleep", "3600" ]
      volumeMounts:
        - name: secret
          mountPath: "/datadir"
          readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: mysecret

